"""create current storage schema"""
from alembic import op
import sqlalchemy as sa

revision = '66cb471014e5'
down_revision = '0001_storage_baseline'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_run',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('requested_symbols', sa.Integer(), nullable=False),
    sa.Column('success_symbols', sa.Integer(), nullable=False),
    sa.Column('failed_symbols', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('yfinance_version', sa.String(length=32), nullable=True),
    sa.Column('schema_version', sa.String(length=32), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('local_code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_symbol'), 'instrument', ['symbol'], unique=True)
    op.create_table('universe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('universe_type', sa.String(length=40), nullable=False),
    sa.Column('as_of_date', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('fund_holding_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_instrument_id', sa.Integer(), nullable=False),
    sa.Column('report_period_end', sa.String(length=10), nullable=False),
    sa.Column('published_date', sa.String(length=10), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('disclosed_weight', sa.Float(), nullable=True),
    sa.Column('holdings_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fund_instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_instrument_id', 'report_period_end')
    )
    op.create_table('fund_instrument_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_instrument_id', sa.Integer(), nullable=False),
    sa.Column('related_instrument_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('report_period_end', sa.String(length=10), nullable=False),
    sa.Column('published_date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['fund_instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['related_instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_run_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('dataset_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('skipped_duplicate_count', sa.Integer(), nullable=False),
    sa.Column('first_data_time', sa.String(length=64), nullable=True),
    sa.Column('latest_data_time', sa.String(length=64), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('quality_metrics_json', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_bar_observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('bar_time', sa.DateTime(), nullable=False),
    sa.Column('market_date', sa.String(length=10), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adjusted_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('dividends', sa.Float(), nullable=True),
    sa.Column('stock_splits', sa.Float(), nullable=True),
    sa.Column('capital_gains', sa.Float(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('upstream_group', sa.String(length=64), nullable=False),
    sa.Column('source_event_time', sa.DateTime(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'interval', 'bar_time', 'provider', 'payload_hash')
    )
    op.create_index(op.f('ix_market_bar_observation_bar_time'), 'market_bar_observation', ['bar_time'], unique=False)
    op.create_index(op.f('ix_market_bar_observation_instrument_id'), 'market_bar_observation', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_market_bar_observation_market_date'), 'market_bar_observation', ['market_date'], unique=False)
    op.create_index(op.f('ix_market_bar_observation_payload_hash'), 'market_bar_observation', ['payload_hash'], unique=False)
    op.create_table('universe_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('membership_type', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('valid_from', sa.String(length=10), nullable=True),
    sa.Column('valid_to', sa.String(length=10), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('universe_id', 'instrument_id')
    )
    op.create_table('fund_holding_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('stock_instrument_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['fund_holding_report.id'], ),
    sa.ForeignKeyConstraint(['stock_instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_holding_position')
    op.drop_table('universe_instrument')
    op.drop_index(op.f('ix_market_bar_observation_payload_hash'), table_name='market_bar_observation')
    op.drop_index(op.f('ix_market_bar_observation_market_date'), table_name='market_bar_observation')
    op.drop_index(op.f('ix_market_bar_observation_instrument_id'), table_name='market_bar_observation')
    op.drop_index(op.f('ix_market_bar_observation_bar_time'), table_name='market_bar_observation')
    op.drop_table('market_bar_observation')
    op.drop_table('ingestion_run_item')
    op.drop_table('fund_instrument_relation')
    op.drop_table('fund_holding_report')
    op.drop_table('universe')
    op.drop_index(op.f('ix_instrument_symbol'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_table('ingestion_run')
    # ### end Alembic commands ###
